### ISSUE TITLE
can not load such file googleauth

### ISSUE THREAD

**Issue by Anandshr** [decision-labs/fcm#100]
When I am installing fcm version 1.0.7 getting this error when I used to start rails server can not load such file google auth...

**Comment by sabman** [comment]
Can you show the output of `bundle add fcm`

It should have the following
```
...
Installing os 1.1.4
Installing signet 0.16.1
Fetching googleauth 1.1.2
Installing googleauth 1.1.2
Fetching fcm 1.0.7
Installing fcm 1.0.7
```

**Comment by smaziano** [comment]
Hey @Anandshr did you setup the GOOGLE_APPLICATION_CREDENTIALS_PATH ?

**Comment by fahad-abbas9** [comment]
I am also facing the same issue, my FCM gem version being installed is 1.0.5 and I don't see the required dependencies, installed with FCM gem, being listed in the gemfile here.

**Comment by rafaeljcadena** [comment]
I installed googleauth gem and it worked

The gem:
gem 'googleauth'
