### ISSUE TITLE
Where to find Firebase API_Token ?

### ISSUE THREAD

**Issue by adriano-silva** [decision-labs/fcm#109]
Hello, I'm new to FCM and therefore to your project.

My question is about the the "API_TOKEN" required for the FCM initialisation. 
Where can I find this token in Firebase? Is it not already in the json of "GOOGLE_APPLICATION_CREDENTIALS_PATH" ?
Looking at the code, I see that it requires the "SERVER_KEY" from the legacy API, but what's the point of mixing legacy with new API?

**Comment by jjvillavicencio** [comment]
Hello, I have the same question, any answer?

**Comment by sabman** [comment]
Guys we are working on a new release, hopefully next week. See this PR https://github.com/decision-labs/fcm/pull/107 this separates the legacy and the new API.

**Comment by akshay-thence** [comment]
> Looks like currently the API key gets overwritten anyway in `send_v1` so simply passing `nil` should work.

Its working, We can close this issue.

**Comment by the-bass** [comment]
Thanks for everyone involved for providing this gem!

As someone new to this gem and Firebase in general, though, pointing out that - at least for users of `send_v1` - this parameter is irrelevant somewhere in the Readme would have saved me quite some time. Maybe you can do that for future users?
