### ISSUE TITLE
how to create API token

### ISSUE THREAD

**Issue by venkateshrj12** [decision-labs/fcm#119]
as per new version of FCM, while initializing we need to provide 3 values, one of them is API_TOKEN, can anyone please tell me that how can i generate or get the API_TOKEN to pass here?

**Comment by piotrekp2fieldly** [comment]
cc @sabman, the same question as ⬆️

**Comment by nerixim** [comment]
Hey guys. I haven't checked this myself, but looks like you don't need API_KEY, just pass `nil` as the first argument.
https://github.com/decision-labs/fcm/pull/115

**Comment by Startouf** [comment]
So if there is no API_KEY, how do we authenticate ?

**Comment by sabman** [comment]
For now you could try this https://github.com/decision-labs/fcm/issues/110#issuecomment-1354340105 longer term we would need to make a change that allows API_TOKEN to be passed in via env vars or some kind of fall back to a config file.

**Comment by sabman** [comment]
Wait are you asking about minting the token? please see https://firebase.google.com/docs/cloud-messaging/auth-server#:~:text=.%20To%20mint%20this%20token%2C%20you%20can%20use%20Google%20Application%20Default%20Credentials

**Comment by Kunj-Choksi** [comment]
Passing `nil` for API_TOKEN worked for me, Thanks Guys!

**Comment by venkateshrj12** [comment]
Thanks Guys!, Passing `nil` for API_TOKEN worked for me,

But i did not get that why we need to pass the API_TOKEN if it is not required?

**Comment by sabman** [comment]
new release supports bearer tokens https://github.com/decision-labs/fcm/pull/123#issuecomment-2358298417
