### ISSUE TITLE
Error: Deprecated FCM Endpoint During Migration to v1 API When Using send_to_topic

### ISSUE THREAD

**Issue by tuanbacyen** [decision-labs/fcm#124]
The request endpoint has been changed from `/fcm/send` to `/v1/projects/project-id/messages:send`
Now, when use the send_to_topic method got a error
```
{
  :body=>"{"error":"Deprecated endpoint, see https://firebase.google.com/docs/cloud-messaging/migrate-v1"}",
  :headers=>{...},
  :status_code=>301
}
```

However, the `fcm` gem is still using the old sending method:
``` ruby
send_to_topic -> send_with_notification_key -> execute_notification
```
In the `execute_notification` method, the old endpoint (`/fcm/send`) and parameters are still in use
You must rewrite the function or add new methods for sending messages to a topic to work properly.
Here is a class where I added new methods for send topic to work again.

1, Firstly add the connection headers confign
``` ruby
# remove old headers
faraday.headers["Authorization"] = "key=#{api_key}"

# add new headers
faraday.headers['Authorization'] = "Bearer #{jwt_token}"
faraday.headers['access_token_auth'] = 'true'
```

2, The next define the method execute_notification_v1
``` ruby
# This function can be used for send_notification_v1
def execute_notification_v1(message)
  post_body = { message: }
  for_uri(BASE_URI_V1) do |connection|
    response = connection.post("#{@project_name}/messages:send", post_body.to_json)
    build_response(response)
  end
end
```

3, The last define the method send_to_topic_v1
  - The old method use the payload `body = { to: notification_key }.merge(options)` but on new method keyword `to` deprecate, using topic in message
  - Information here: https://firebase.google.com/docs/cloud-messaging/migrate-v1#update-the-payload-of-send-requests

``` ruby
def send_to_topic_v1(topic, options = {})
  return unless topic.gsub(TOPIC_REGEX, '').length.zero?

  body = { topic: }.merge(options)
  execute_notification_v1(body)
end
```

- These changes got my project working properly again. Hope they help you.

## Implement class FcmV1
``` ruby
class FcmV1 < FCM
  attr_accessor :json_key_path, :project_name

  def initialize(json_key_path:, project_name:)
    super(nil)
    @json_key_path = json_key_path
    @project_name = project_name
  end

  def send_to_topic_v1(topic, options = {})
    return unless topic.gsub(TOPIC_REGEX, '').length.zero?

    body = { topic: }.merge(options)
    execute_notification_v1(body)
  end

  private

  def for_uri(uri, extra_headers = {})
    connection = ::Faraday.new(
      url: uri,
      request: { timeout: DEFAULT_TIMEOUT }
    ) do |faraday|
      faraday.adapter Faraday.default_adapter
      faraday.headers['Content-Type'] = 'application/json'
      faraday.headers['Authorization'] = "Bearer #{jwt_token}"
      faraday.headers['access_token_auth'] = 'true'
      extra_headers.each do |key, value|
        faraday.headers[key] = value
      end
    end
    yield connection
  end

  def execute_notification_v1(message)
    post_body = { message: }
    for_uri(BASE_URI_V1) do |connection|
      response = connection.post("#{@project_name}/messages:send", post_body.to_json)
      build_response(response)
    end
  end
end
```

**Comment by aap17** [comment]
I forked the lib and made bug fix, while pull request is not accepted

https://github.com/aap17/fcm_v1

**Comment by sabman** [comment]
new release now merged https://rubygems.org/gems/fcm
https://github.com/decision-labs/fcm/releases/tag/v2.0.0

Thanks to all the awesome contributions!
