### ISSUE TITLE
v1 doesn't support send to multiple tokens anymore ( any workarounds beside pub/sub ? )

### ISSUE THREAD

**Issue by takeda-ma** [decision-labs/fcm#126]
I am currently migrating from legacy http to v1 http, but I encounter this problem where v1 looks like it doesn't accept array of tokens to send to.

similar to this person
https://groups.google.com/g/firebase-talk/c/4GuTzvRT_10?pli=1

after researching a bit it seems like the better practice is to do a pub/sub 
where I need to make each device subscribe to a specific topic, 
and then just broadcast a single message that will target those who are subscribe to the topic.
But I believe this will change our system a bit because we now want to be able to store the data of users which are currently
subscribed to a specific topic. ( We could maybe do a dirty implementation of temporarily subscribing tokens -> send message -> then unsubscribe all of them,,, but I believe this is not what firebase want us to do... or am I wrong)

**Comment by aap17** [comment]
https://github.com/decision-labs/fcm/issues/122

**Comment by takeda-ma** [comment]
firebase suggest the following
for 1 million recipients -> it is better to fanout 

for less than 1 million recipients or whatever is advantageous to migrate to fanout for you-> it is better to send request 

source:https://firebase.google.com/support/faq#fcm-depr-multiple-tokens
