### ISSUE TITLE
Faraday::ConnectionFailed & Net::OpenTimeout

### ISSUE THREAD

**Issue by Ahmed-Salama96** [decision-labs/fcm#131]
Faraday sometimes raises a timeout error. We need to increase it a bit

**Comment by Ahmed-Salama96** [comment]
![Screenshot 2024-10-21 at 2 02 28 PM](https://github.com/user-attachments/assets/3db53432-1a3c-4151-980e-b1785d24d16a)
Since I'm not a contributor, here is my suggestion for the issue I faced

**Comment by Ahmed-Salama96** [comment]
![Screenshot 2024-10-21 at 2 03 31 PM](https://github.com/user-attachments/assets/204b0b6c-98f1-45cf-b0d1-62b9161a9221)

**Comment by sabman** [comment]
@Ahmed-Salama96 thanks for the suggestion can you try out this branch https://github.com/decision-labs/fcm/pull/132 and suggest if it fixes the issue?

**Comment by Ahmed-Salama96** [comment]
Thanks @sabman. That works well

**Comment by sabman** [comment]
new release pushed https://rubygems.org/gems/fcm/versions/2.0.1
