### ISSUE TITLE
Invalid Registration IOS

### ISSUE THREAD

**Issue by ademir10** [decision-labs/fcm#82]
Hi guys!
I'm facing a problem when i try to send a notification to IOS devices:
"results\":[{\"error\":\"InvalidRegistration\"}]}", 

But it happens only to IOS devices, to Android it's working fine.
Do you know what can i do to fix it?

To have sure about my APNS certificate, i generate a new certificate and added to firebase, but nothing changes..

I'm using the last FCM gem vesion too 1.0.2
Do you have any suggestion?
thanks!

**Comment by abwahed** [comment]
I am facing the same problem. using the same version.
@ademir10, did you find a solution for this anyway?

**Comment by ademir10** [comment]
Hello!
No, i don't found a way to fix it, still not working in IOS.
Couple weeks a go a found a article telling about it, Apple make some changes and after that it stop to work, i think we need to use another way to keep using firebase to IOS devices.

Let me know if you found any another way, i still need to fix it too..

**Comment by lloydwatkin** [comment]
@ademir10 have you converted your APNs token to an FCM one?

**Comment by ap-hughes** [comment]
We were having this same issue, built a backend API and our Frontend developers were passing us device_token, all seemed like it should work. 200 success from Firebase, but an error of `InvalidRegistration`. After a frustrating day, front-end passed us the `fcmToken`, not the apple device token. Sure enough .. this worked. 

I think the language in places is a bit confusing, we were so focussed on the idea of a `device token`, hadn't appreciated that when setting up Apple APN on firebase, etc. we should be using the fcm token instead..

For reference, the token _may_ look a little like this:

`"eDw9ELmTnU0LmByZuMvff3:APA91bFu_Om9Z5lq_LU7VK2HUhK2Fly8reRfgLacoVElTCmkprP
iUN9loXf4GbS_3cH8AP4oTAfC2CWWWshKInF52jye93EgqBSLhXzUIH0hl5KFc1RMV8_UgxCsdPFKPbGSA9lcP8W3"`

**Comment by ademir10** [comment]
> We were having this same issue, built a backend API and our Frontend developers were passing us device_token, all seemed like it should work. 200 success from Firebase, but an error of `InvalidRegistration`. After a frustrating day, front-end passed us the `fcmToken`, not the apple device token. Sure enough .. this worked.
> 
> I think the language in places is a bit confusing, we were so focussed on the idea of a `device token`, hadn't appreciated that when setting up Apple APN on firebase, etc. we should be using the fcm token instead..
> 
> For reference, the token _may_ look a little like this:
> 
> `"eDw9ELmTnU0LmByZuMvff3:APA91bFu_Om9Z5lq_LU7VK2HUhK2Fly8reRfgLacoVAlTDmkprP iUN9loXf4GbS_3cH8AP4oTAfC2CWWWshKInF52jye93EgqBSLhXzUIH0hl5KFc1RMV8_PgxCsdPFKPbGSA9lcP8W3"`

Hello my friend!
thank you for the tip!
I'm still facing the same problem.

Could you help me with my firebase config?
Im using the server key generated by firebase in my back end, and using the token device generated in my front end (App) to convert it in a FCM, it's working perfect to android devices, but no way when i try to send push notifications to iOS devices:
this is my code:
        fcm = FCM.new(@server_key.server_key_firebase) # server_key on: your firebase console on web > tab general > web api key
        registration_ids= [destinatario.token] # Array of keys generated by firebase for devices (HERE I HAVE THE TOKEN DEVICE)
        options = {
            priority: "high",
              notification: {
              title: params[:title],
              body: params[:message],
              sound: 'default',
              icon: 'favicon.ico' }
            }
            response = fcm.send(registration_ids, options)

![Captura de Tela 2021-04-14 às 10 16 12](https://user-images.githubusercontent.com/2720896/114716474-769a7580-9d0a-11eb-80d0-e9d450bd127c.png)

**Comment by ap-hughes** [comment]
Hi, I think your FCM config looks OK and should work for iOS too.

Unfortunately I didn't deal with the app config directly, so probably not much help on the iOS setup in Firebase. Are you able to send a test notification to the device directly from the Firebase Console? If not, then you could probably debug and it might be something to do with the certificate or setup within Firebase.

Also, I would suggest removing your screengrab of Firebase, just to be safe, as it has exposed API keys.

**Comment by ademir10** [comment]
> Hi, I think your FCM config looks OK and should work for iOS too.
> 
> Unfortunately I didn't deal with the app config directly, so probably not much help on the iOS setup in Firebase. Are you able to send a test notification to the device directly from the Firebase Console? If not, then you could probably debug and it might be something to do with the certificate or setup within Firebase.
> 
> Also, I would suggest removing your screengrab of Firebase, just to be safe, as it has exposed API keys.

Finally fixed!
I had the same problem with the token generated by the App, after to change the plugin used to generate FCM token everything worked.

Thank you my dear friend!
