### ISSUE TITLE
Tag a new release for Faraday updates

### ISSUE THREAD

**Issue by samsonjs** [decision-labs/fcm#88]
We're still using fcm 0.0.6 because 1.0.2 is locked to Faraday 1.0.0, and we're using Faraday 1.4.1. The gemspec is all updated and it looks like a new release of what's currently on master is all that's required to get fcm working with a current version of Faraday.

**Comment by sabman** [comment]
Thanks for the prompt all. Released https://github.com/decision-labs/fcm/releases/tag/v1.0.3

**Comment by samsonjs** [comment]
This is great. Thank you!
