### ISSUE TITLE
Schedule for new release

### ISSUE THREAD

**Issue by mannodermaus** [decision-labs/fcm#97]
Hello, thank you for providing this gem! I'd like to leverage the benefits merged via #94 and was wondering if a new release is on the horizon? For now, I'm declaring the latest commit in my `Gemfile`, but ideally I'd prefer a version constant:

```
gem 'fcm', :git => 'git://github.com/decision-labs/fcm.git', :ref => 'c2285ff5b522a30cf6f4886c138c552215df4800'
```

Thanks in advance!

**Comment by sabman** [comment]
@mannodermaus I'll push a new release today. Sorry for the delay

**Comment by sabman** [comment]
https://github.com/decision-labs/fcm/releases

**Comment by mannodermaus** [comment]
Much appreciated, thank you! Have a good one. 🙏
