### ISSUE TITLE
Faraday 2.0

### ISSUE THREAD

**Issue by maszuDEV** [decision-labs/fcm#99]
Hello guys, big thanks for your hard work here!

Do you have any plans to release support for Faraday 2?

Best!

**Comment by sabman** [comment]
@maszuDEV yes its on the backlog. I'll post the upgrade link here for reference incase anyone wants to create a PR. https://github.com/lostisland/faraday/blob/main/UPGRADING.md

**Comment by sabman** [comment]
https://github.com/decision-labs/fcm/pull/101
